openapi: 3.0.0
info:
  title: Cluster Deployment Service API
  version: "1.0.0"
  description: API documentation for Authen & Author module

paths:
  /auth/register:
    post:
      summary: Register and get token
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: Tokens returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  renew_token:
                    type: string

  /auth/renew:
    post:
      summary: Renew access token
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                renew_token:
                  type: string
              required:
                - renew_token
      responses:
        "200":
          description: New access token returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string

  /auth/validate:
    post:
      summary: Validate user credentials
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: Valid user
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
