openapi: 3.0.3
info:
  title: Auth Service API
  version: 1.0.0
  description: API quản lý secret key và token cho dịch vụ
servers:
  - url: http://localhost:8080
    description: Local server

tags:
  - name: SecretKey
    description: API tạo và lấy secret key
  - name: Token
    description: API quản lý token

paths:
  /api/secretkey:
    post:
      summary: Tạo secret key mới
      tags: [SecretKey]
      responses:
        '200':
          description: Secret key được tạo thành công
          content:
            application/json:
              schema:
                type: object
                example:
                  uuid: "1b01cf34-0cdb-4e07-aac5-488ff894d050"
                  secretKey: "abc123xyz"
  /api/register:
    post:
      summary: Tạo token mới với secret key
      tags: [Token]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTokenRequest'
      responses:
        '200':
          description: Token được tạo thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  secretKey:
                    type: string
                    example: "abc123xyz"
  /api/fulltoken:
    get:
      summary: Lấy toàn bộ token
      tags: [Token]
      responses:
        '200':
          description: Danh sách token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
  /api/revoketoke:
    put:
      summary: Thu hồi 1 token theo UUID
      tags: [Token]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                uuid:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Token đã được thu hồi
          content:
            application/json:
              schema:
                type: string
                example: "revoke"
  /api/revoketokenfull:
    put:
      summary: Thu hồi toàn bộ token
      tags: [Token]
      responses:
        '200':
          description: Toàn bộ token đã được thu hồi
          content:
            application/json:
              schema:
                type: string
                example: "revokeAll"
  /api/activetokenfull:
    put:
      summary: Active toàn bộ token
      tags: [Token]
      responses:
        '200':
          description: Toàn bộ token đã được active
          content:
            application/json:
              schema:
                type: string
                example: "ActiveAll"

components:
  schemas:
    CreateTokenRequest:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          example: "1b01cf34-0cdb-4e07-aac5-488ff894d050"
        serviceName:
          type: string
          example: "my-service"
        ttl:
          type: integer
          example: 3600
    TokenItem:
      type: object
      properties:
        UUID:
          type: string
          format: uuid
          example: "4176da37-a488-43bf-805e-343e52b67b47"
        Service:
          type: string
          example: ""
        Exp:
          type: integer
          example: 1754822735
        Iat:
          type: integer
          example: 1754822735
        HashToken:
          type: string
          example: "360171af5affb1ea982f75ad71df99b84e9fdcec2468d6b9d23062ae01a32d7a"
        Status:
          type: string
          example: "active"
    TokenResponse:
      type: object
      properties:
        token:
          type: array
          items:
            $ref: '#/components/schemas/TokenItem'
      example:
        token:
          - UUID: "4176da37-a488-43bf-805e-343e52b67b47"
            Service: ""
            Exp: 1754822735
            Iat: 1754822735
            HashToken: "360171af5affb1ea982f75ad71df99b84e9fdcec2468d6b9d23062ae01a32d7a"
            Status: "active"
          - UUID: "43940663-3b53-4ddb-8710-212c3d993b29"
            Service: ""
            Exp: 1754822769
            Iat: 1754822769
            HashToken: "19c708906ee86284048c7ca9b1629056ea4b41b245de8201981ccc783acd40c4"
            Status: "active"
